# Generated by Django 5.1.7 on 2025-04-16 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ciclo',
        ),
        migrations.DeleteModel(
            name='TipoTarea',
        ),
    ]
