# Generated by Django 5.2 on 2025-05-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devocionales',
            fields=[
                ('id_devocional', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.CharField(max_length=20)),
                ('año', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('titulo', models.TextField()),
                ('texto_biblico', models.TextField()),
                ('reflexion', models.TextField()),
                ('contenido_calendario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'devocionales',
                'managed': False,
            },
        ),
    ]
